### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'palette'

### ISSUE THREAD

**Issue by carden-code** [x-hw/amazing-qr#114]
amzqr https://github.com -v 10 -p imgonline-com-ua-GIF-Animation-65norxj0k3JcR.gif -n animated_qrcode.gif

It may take a while, please wait for minutes...
line 16: mode: byte
Traceback (most recent call last):
  File "/home/vyacheslav/avito/qrcode/venv/bin/amzqr", line 8, in <module>
    sys.exit(main())
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/amzqr/terminal.py", line 25, in main
    ver, ecl, qr_name = run(
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/amzqr/amzqr.py", line 117, in run
    imageio.mimwrite(qr_name, ims, '.gif', **{ 'duration': duration/1000 })
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/imageio/v2.py", line 483, in mimwrite
    with imopen(uri, "wI", **imopen_args) as file:
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/imageio/core/v3_plugin_api.py", line 367, in __exit__
    self.close()
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/imageio/plugins/pillow.py", line 120, in close
    self._flush_writer()
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/imageio/plugins/pillow.py", line 428, in _flush_writer
    primary_image.save(self._request.get_file(), **self.save_args)
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/PIL/Image.py", line 2432, in save
    save_handler(self, fp, filename)
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/PIL/GifImagePlugin.py", line 653, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/PIL/GifImagePlugin.py", line 664, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/PIL/GifImagePlugin.py", line 643, in _write_multiple_frames
    _write_frame_data(fp, im_frame, offset, frame_data["encoderinfo"])
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/PIL/GifImagePlugin.py", line 975, in _write_frame_data
    _write_local_header(fp, im_frame, offset, 0)
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/PIL/GifImagePlugin.py", line 730, in _write_local_header
    palette_bytes = _get_palette_bytes(im)
  File "/home/vyacheslav/avito/qrcode/venv/lib/python3.10/site-packages/PIL/GifImagePlugin.py", line 882, in _get_palette_bytes
    return im.palette.palette
AttributeError: 'NoneType' object has no attribute 'palette'

**Comment by cys138138** [comment]
您好，你的邮件我已收到！

**Comment by zhangtinghai** [comment]
收到。。

**Comment by kuaij** [comment]
您好！

    您正在找回密码，为确保是你本人操作，请在邮箱验证码输入框输入下方验证码：


    
        
            658360
        
    


        如果这不是你本人所为，请忽略。请勿向任何人泄漏您收到的验证码。


    
        
    


        冬奥小助 账号团队敬上

**Comment by carden-code** [comment]
658360

**Comment by carden-code** [comment]
-c should have been put at the end
